apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: registry
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`${DOMAIN}`)
    services:
    - name: registry
      port: 5000
  tls:
    certResolver: default
