all:
  children:
    proxmox:
      hosts:
        proxmox1:
      children:
        proxmox_master:
          hosts:
            proxmox1:
    k3s:
      hosts:
        k3s-201:
        k3s-202:
        k3s-203:
      children:
        k3s_master:
          hosts:
            k3s-201:
        k3s_worker:
          hosts:
            k3s-202:
            k3s-203:


