- name: k3s node 101
  include_role:
    name: kvm_instance
  vars:
    id: 101
    host: nuc3
    user: root
    name: k3s-101
    size: m1.small
    volumes:
      root: 20G
    sshkeys: "{{ core_ssh_keys }}"

