apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-data
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_SIZE}
  storageClassName: local-path
