apiVersion: v1
kind: Service
metadata:
  name: drone
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
  selector:
    app: drone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drone
  name: drone
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
      - image: ${IMAGE}
        name: drone
        volumeMounts:
          - name: data
            mountPath: /data
        ## debug:
        ## command: ["/bin/sh", "-c", "sleep 99999999999"]
        ports:
        - containerPort: 80
          name: web
        env:
          - name: DRONE_GITEA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_GITEA_CLIENT_ID
          - name: DRONE_GITEA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_GITEA_CLIENT_SECRET
          - name: DRONE_GITEA_SERVER
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_GITEA_SERVER
          - name: DRONE_GIT_ALWAYS_AUTH
            value: "${DRONE_GIT_ALWAYS_AUTH}"
          - name: DRONE_RPC_SECRET
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_RPC_SECRET
          - name: DRONE_SERVER_HOST
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_SERVER_HOST
          - name: DRONE_SERVER_PROTO
            value: https
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: drone-data
