# Name of cluster to create
proxmox_cluster: pve

proxmox_master_node: nuc3
proxmox_domain: "app.shln.rymcg.tech"
proxmox_root: "root@pam"
proxmox_public_interface: eno1
proxmox_trunk_interface: vmbr0
promox_public_network: 10.13.13.0/24
proxmox_master_ip: 10.13.13.11
proxmox_public_netmask: 255.255.255.0
proxmox_public_gateway: 10.13.13.1
## Read the root password from the vault, don't change this here:
proxmox_root_password: "{{ vault_proxmox_root_password }}"
## Read ssh public keys from vault (unnecessary except to conceal identities).
## These are default keys for VMs unless otherwise specified
## (don't change this, edit the vault instead):
core_ssh_keys: "{{ vault_core_ssh_keys }}"

## Specify external IPs allowed to access the dashboard:
## If you do this on public network, you MUST setup TLS/SSL!!
proxmox_external_client_subnets: []

## Configure Proxmox client (ansible) to require trusted TLS.
## Default is False, because the client accesses localhost API and thus unnecessary.
proxmox_client_verify_ssl: False

proxmox_kvm_admin: "root@pam"
## Read the root password from the vault, don't change this here:
proxmox_kvm_admin_password: "{{ vault_proxmox_root_password }}"

ubuntu_focal_cloud_image_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
ubuntu_focal_cloud_image: /var/lib/vz/template/iso/focal-server-cloudimg-amd64.img

proxmox_template_ids:
  ubuntu_focal: 9000

### Proxmox KVM instance sizes:
### (names are loosly based off AWS instance sizes)
proxmox_instance_sizes:
  m1.nano:
    ram: 0.5
    cpu: 1
  m1.micro:
    ram: 1
    cpu: 1
  m1.small:
    ram: 2
    cpu: 2
  m1.medium:
    ram: 4
    cpu: 2
  m1.large:
    ram: 8
    cpu: 2
  m1.xlarge:
    ram: 16
    cpu: 4
  c1.small:
    ram: 2
    cpu: 4
  c1.medium:
    ram: 4
    cpu: 4
  c1.large:
    ram: 8
    cpu: 4
  c1.xlarge:
    ram: 16
    cpu: 6
