apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`${DOMAIN}`)
    services:
    - name: gitea
      port: 80
  tls:
    certResolver: default
