apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
  selector:
    app: gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - image: ${IMAGE}
        name: gitea
        volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /data/gitea/conf
        ports:
        - containerPort: 3000
          name: web
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: config
          configMap:
            name: gitea
