apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/traefik
patchesJson6902:
- target:
    version: v1
    kind: PersistentVolumeClaim
    namespace: kube-system
    name: traefik-data
  path: 020-traefik-pvc-patch.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    namespace: kube-system
    name: traefik
  path: 030-traefik-daemonset-patch.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    namespace: kube-system
    name: traefik
  path: 031-traefik-daemonset-ssh-patch.yaml
