apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drone-digitalocean-runner
  name: drone-digitalocean-runner
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-digitalocean-runner
  template:
    metadata:
      labels:
        app: drone-digitalocean-runner
    spec:
      serviceAccountName: drone-runner
      containers:
      - image: ${DIGITALOCEAN_RUNNER_IMAGE}
        name: drone-digitalocean-runner
        volumeMounts:
          - name: config
            mountPath: /data/drone/conf
        env:
          - name: DRONE_RPC_SECRET
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_RPC_SECRET
          - name: DRONE_RPC_HOST
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_SERVER_HOST
          - name: DRONE_RPC_PROTO
            value: https
          - name: DRONE_SECRET_PLUGIN_ENDPOINT
            value: http://drone-secrets-plugin.${NAMESPACE}.svc.cluster.local:3000
          - name: DRONE_SECRET_PLUGIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_KUBERNETES_SECRET_KEY
          - name: DRONE_PUBLIC_KEY_FILE
            value: /data/drone/conf/id_rsa.pub
          - name: DRONE_PRIVATE_KEY_FILE
            value: /data/drone/conf/id_rsa
      volumes:
        - name: config
          secret:
            secretName: drone
            items:
              - key: id_rsa.pub.yaml
                path: id_rsa.pub
              - key: id_rsa.yaml
                path: id_rsa

