apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/whoami
patchesJson6902:
- target:
    group: "traefik.containo.us"
    version: "v1alpha1"
    kind: IngressRoute
    namespace: default
    name: whoami
  path: 20-whoami-ingress-route-patch.yaml
