apiVersion: v1
kind: Endpoints
metadata:
  name: ssh
subsets:
- addresses:
  - ip: 10.5.0.1
  ports:
  - port: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
  selector:
    app: ssh
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ssh
  namespace: default
spec:
  entryPoints:
  - ssh
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - name: ssh
      port: 2222
